### ISSUE TITLE
Number exception 

### ISSUE THREAD

**Issue by Yoshimanly** [caseyscarborough/qbittorrent-exporter#15]
In browser this is the error it throws:

![image](https://user-images.githubusercontent.com/37461591/224155341-d3830b29-2445-446c-80f6-4160fba9426f.png)

An error occurred. For input string: "10,50"

I read the issues and one is very close to this one, but I'm not able to find where this number comes from to change it

These are the Docker logs

20:53:48.470 [INFO] qbittorrent.exporter.handler.QbtHttpHandler - Beginning prometheus metrics collection...
20:53:48.558 [INFO] qbittorrent.api.ApiClient - Response from /torrents/info endpoint was 200.
20:53:48.579 [INFO] qbittorrent.api.ApiClient - Response from /app/preferences endpoint was 200.
20:53:48.696 [INFO] qbittorrent.api.ApiClient - Response from /sync/maindata endpoint was 200.
20:53:48.705 [INFO] qbittorrent.api.ApiClient - Response from /app/version endpoint was 200.
20:53:48.706 [ERROR] qbittorrent.exporter.handler.QbtHttpHandler - An error occurred calling API
java.lang.NumberFormatException: For input string: "10,50"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at qbittorrent.exporter.handler.QbtHttpHandler.handleRequest(QbtHttpHandler.java:53) [qbittorrent-exporter.jar:?]
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104) [undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) [undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256) [undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) [undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) [undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) [xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) [xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) [xnio-nio-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) [xnio-nio-3.8.6.Final.jar:3.8.6.Final]

**Comment by Yoshimanly** [comment]
Found it, but no able to work around it

![image](https://user-images.githubusercontent.com/37461591/224168119-b5acd477-5378-461f-99fc-da438573c6a6.png)

**Comment by Yoshimanly** [comment]
Yo, resolved this issue.

What happens is that based on the region formatting it changes from a "." to a "," and it breaks your code


![image](https://user-images.githubusercontent.com/37461591/224555063-878103c3-196b-413c-b6d1-6e711c0a0afb.png)

**Comment by danilodorgam** [comment]
I have the same situation

**Comment by vincejv** [comment]
@Yoshimanly @danilodorgam 
you may try to temporarily use my docker image which try to address the locale issue, use `fr-FR` as `QBITTORRENT_LOCALE`, this container is built on my fork https://github.com/vincejv/qbittorrent-exporter
```yaml
version: "3"
services:
 qbt-exporter:
    image: vincejv/qbittorrent-exporter:latest
    container_name: qbt-exporter
    networks:
      int-static-br:
        ipv4_address: 172.18.0.34
    environment:
      - QBITTORRENT_USERNAME=none
      - QBITTORRENT_PASSWORD=none
      - QBITTORRENT_BASE_URL=http://qbt.docker.internal:9089
      - QBITTORRENT_LOCALE=fr-FR
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - qbittorrent
    logging:
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"
```
