### ISSUE TITLE
[Feature Request]: Include Categories/Tags/Trackers in info

### ISSUE THREAD

**Issue by Inrixia** [caseyscarborough/qbittorrent-exporter#17]
It would be great if it was possible to have this information for filtering/displaying especially if you wanted to track info for different trackers/categories etc like sonarr/radarr and so on

**Comment by vincejv** [comment]
@Inrixia does this address your Feature request?
A torrent can have multiple tags, as per QBT Api, it will return it as CSV (Comma separated value)

You may pull my docker image at `vincejv/qbittorrent-exporter:latest`, see sample docker compose below, it is built on my fork: https://github.com/vincejv/qbittorrent-exporter
![image](https://github.com/caseyscarborough/qbittorrent-exporter/assets/1276544/234e8f06-cb20-46ef-a42d-5fd868048d53)

```yaml
version: "3"
services:
 qbt-exporter:
    image: vincejv/qbittorrent-exporter:latest
    container_name: qbt-exporter
    networks:
      int-static-br:
        ipv4_address: 172.18.0.34
    environment:
      - QBITTORRENT_USERNAME=none
      - QBITTORRENT_PASSWORD=none
      - QBITTORRENT_BASE_URL=http://qbt.docker.internal:9089
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - qbittorrent
    logging:
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"
```
